This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./Tese_Joana.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Tese_Joana.acn....done (134 entries accepted, 0 rejected).
Sorting entries....done (1079 comparisons).
Generating output file Tese_Joana.acr....done (97 lines written, 0 warnings).
Output written in Tese_Joana.acr.
Transcript written in Tese_Joana.alg.
