CREATE DATABASE cl_10001;
USE cl_10001;
CREATE TABLE clientes
(
    cl_ID INT NOT NULL,
    cl_nome VARCHAR(50) NOT NULL,
    cl_morada VARCHAR(100),
    cl_IP VARCHAR(50) NOT NULL,
    cl_port INT NOT NULL,
    CONSTRAINT REPETIDO_ID_CLIENTE
	PRIMARY KEY(cl_ID)
);
CREATE TABLE moldes
(
    m_IDCliente INT NOT NULL,
    m_ID INT NOT NULL,
    m_nome VARCHAR(30),
    m_descricao VARCHAR(200),
    CONSTRAINT REPETIDO_ID_MOLDE
	PRIMARY KEY(m_ID),
    CONSTRAINT MOLDE_MAU_ID_CLIENTE
	FOREIGN KEY(m_IDCliente) REFERENCES clientes(cl_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE tipo
(
    tipo_ID INT NOT NULL,
    tipo_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_TIPO
	PRIMARY KEY(tipo_ID),
    CONSTRAINT REPETIDO_NOME_TIPO
	UNIQUE(tipo_nome)
);
CREATE TABLE sensores
(
    s_IDMolde INT NOT NULL,
    s_num INT NOT NULL,
    s_tipo INT NOT NULL,
    s_nome varchar(30),
    s_descricao varchar(200),
    CONSTRAINT REPETIDO_NUM_SENSOR
	PRIMARY KEY(s_IDMolde,s_num),
    CONSTRAINT SENSOR_MAU_ID_MOLDE
	FOREIGN KEY(s_IDMolde) REFERENCES moldes(m_ID)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT SENSOR_MAU_ID_TIPO
	FOREIGN KEY(s_tipo) REFERENCES tipo(tipo_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE fase
(
    fase_ID INT NOT NULL,
    fase_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_FASE
	PRIMARY KEY(FASE_ID),
    CONSTRAINT REPETIDO_NOME_FASE
	UNIQUE(fase_nome)
);
CREATE TABLE registos
(
    r_IDMolde INT NOT NULL,
    r_numSensor INT NOT NULL,
    r_fase INT NOT NULL,
    r_data_hora DATETIME NOT NULL,
    r_milissegundos TINYINT NOT NULL,
    r_valor FLOAT,
    CONSTRAINT REPETIDO_REGISTO
	PRIMARY KEY(r_IDMolde, r_numSensor, r_data_hora, r_milissegundos),
    CONSTRAINT REGISTOS_MAU_ID_MOLDE_SENSOR
FOREIGN KEY(r_IDMolde,r_numSensor) REFERENCES sensores(s_IDMolde,s_num)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT REGISTOS_MAU_ID_FASE
FOREIGN KEY(r_fase) REFERENCES fase(fase_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE DATABASE cl_10002;
USE cl_10002;
CREATE TABLE clientes
(
    cl_ID INT NOT NULL,
    cl_nome VARCHAR(50) NOT NULL,
    cl_morada VARCHAR(100),
    cl_IP VARCHAR(50) NOT NULL,
    cl_port INT NOT NULL,
    CONSTRAINT REPETIDO_ID_CLIENTE
	PRIMARY KEY(cl_ID)
);
CREATE TABLE moldes
(
    m_IDCliente INT NOT NULL,
    m_ID INT NOT NULL,
    m_nome VARCHAR(30),
    m_descricao VARCHAR(200),
    CONSTRAINT REPETIDO_ID_MOLDE
	PRIMARY KEY(m_ID),
    CONSTRAINT MOLDE_MAU_ID_CLIENTE
	FOREIGN KEY(m_IDCliente) REFERENCES clientes(cl_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE tipo
(
    tipo_ID INT NOT NULL,
    tipo_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_TIPO
	PRIMARY KEY(tipo_ID),
    CONSTRAINT REPETIDO_NOME_TIPO
	UNIQUE(tipo_nome)
);
CREATE TABLE sensores
(
    s_IDMolde INT NOT NULL,
    s_num INT NOT NULL,
    s_tipo INT NOT NULL,
    s_nome varchar(30),
    s_descricao varchar(200),
    CONSTRAINT REPETIDO_NUM_SENSOR
	PRIMARY KEY(s_IDMolde,s_num),
    CONSTRAINT SENSOR_MAU_ID_MOLDE
	FOREIGN KEY(s_IDMolde) REFERENCES moldes(m_ID)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT SENSOR_MAU_ID_TIPO
	FOREIGN KEY(s_tipo) REFERENCES tipo(tipo_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE fase
(
    fase_ID INT NOT NULL,
    fase_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_FASE
	PRIMARY KEY(FASE_ID),
    CONSTRAINT REPETIDO_NOME_FASE
	UNIQUE(fase_nome)
);
CREATE TABLE registos
(
    r_IDMolde INT NOT NULL,
    r_numSensor INT NOT NULL,
    r_fase INT NOT NULL,
    r_data_hora DATETIME NOT NULL,
    r_milissegundos TINYINT NOT NULL,
    r_valor FLOAT,
    CONSTRAINT REPETIDO_REGISTO
	PRIMARY KEY(r_IDMolde, r_numSensor, r_data_hora, r_milissegundos),
    CONSTRAINT REGISTOS_MAU_ID_MOLDE_SENSOR
FOREIGN KEY(r_IDMolde,r_numSensor) REFERENCES sensores(s_IDMolde,s_num)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT REGISTOS_MAU_ID_FASE
FOREIGN KEY(r_fase) REFERENCES fase(fase_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE DATABASE cl_10003;
USE cl_10003;
CREATE TABLE clientes
(
    cl_ID INT NOT NULL,
    cl_nome VARCHAR(50) NOT NULL,
    cl_morada VARCHAR(100),
    cl_IP VARCHAR(50) NOT NULL,
    cl_port INT NOT NULL,
    CONSTRAINT REPETIDO_ID_CLIENTE
	PRIMARY KEY(cl_ID)
);
CREATE TABLE moldes
(
    m_IDCliente INT NOT NULL,
    m_ID INT NOT NULL,
    m_nome VARCHAR(30),
    m_descricao VARCHAR(200),
    CONSTRAINT REPETIDO_ID_MOLDE
	PRIMARY KEY(m_ID),
    CONSTRAINT MOLDE_MAU_ID_CLIENTE
	FOREIGN KEY(m_IDCliente) REFERENCES clientes(cl_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE tipo
(
    tipo_ID INT NOT NULL,
    tipo_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_TIPO
	PRIMARY KEY(tipo_ID),
    CONSTRAINT REPETIDO_NOME_TIPO
	UNIQUE(tipo_nome)
);
CREATE TABLE sensores
(
    s_IDMolde INT NOT NULL,
    s_num INT NOT NULL,
    s_tipo INT NOT NULL,
    s_nome varchar(30),
    s_descricao varchar(200),
    CONSTRAINT REPETIDO_NUM_SENSOR
	PRIMARY KEY(s_IDMolde,s_num),
    CONSTRAINT SENSOR_MAU_ID_MOLDE
	FOREIGN KEY(s_IDMolde) REFERENCES moldes(m_ID)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT SENSOR_MAU_ID_TIPO
	FOREIGN KEY(s_tipo) REFERENCES tipo(tipo_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE fase
(
    fase_ID INT NOT NULL,
    fase_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_FASE
	PRIMARY KEY(FASE_ID),
    CONSTRAINT REPETIDO_NOME_FASE
	UNIQUE(fase_nome)
);
CREATE TABLE registos
(
    r_IDMolde INT NOT NULL,
    r_numSensor INT NOT NULL,
    r_fase INT NOT NULL,
    r_data_hora DATETIME NOT NULL,
    r_milissegundos TINYINT NOT NULL,
    r_valor FLOAT,
    CONSTRAINT REPETIDO_REGISTO
	PRIMARY KEY(r_IDMolde, r_numSensor, r_data_hora, r_milissegundos),
    CONSTRAINT REGISTOS_MAU_ID_MOLDE_SENSOR
FOREIGN KEY(r_IDMolde,r_numSensor) REFERENCES sensores(s_IDMolde,s_num)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT REGISTOS_MAU_ID_FASE
FOREIGN KEY(r_fase) REFERENCES fase(fase_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE DATABASE cl_10004;
USE cl_10004;
CREATE TABLE clientes
(
    cl_ID INT NOT NULL,
    cl_nome VARCHAR(50) NOT NULL,
    cl_morada VARCHAR(100),
    cl_IP VARCHAR(50) NOT NULL,
    cl_port INT NOT NULL,
    CONSTRAINT REPETIDO_ID_CLIENTE
	PRIMARY KEY(cl_ID)
);
CREATE TABLE moldes
(
    m_IDCliente INT NOT NULL,
    m_ID INT NOT NULL,
    m_nome VARCHAR(30),
    m_descricao VARCHAR(200),
    CONSTRAINT REPETIDO_ID_MOLDE
	PRIMARY KEY(m_ID),
    CONSTRAINT MOLDE_MAU_ID_CLIENTE
	FOREIGN KEY(m_IDCliente) REFERENCES clientes(cl_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE tipo
(
    tipo_ID INT NOT NULL,
    tipo_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_TIPO
	PRIMARY KEY(tipo_ID),
    CONSTRAINT REPETIDO_NOME_TIPO
	UNIQUE(tipo_nome)
);
CREATE TABLE sensores
(
    s_IDMolde INT NOT NULL,
    s_num INT NOT NULL,
    s_tipo INT NOT NULL,
    s_nome varchar(30),
    s_descricao varchar(200),
    CONSTRAINT REPETIDO_NUM_SENSOR
	PRIMARY KEY(s_IDMolde,s_num),
    CONSTRAINT SENSOR_MAU_ID_MOLDE
	FOREIGN KEY(s_IDMolde) REFERENCES moldes(m_ID)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT SENSOR_MAU_ID_TIPO
	FOREIGN KEY(s_tipo) REFERENCES tipo(tipo_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE fase
(
    fase_ID INT NOT NULL,
    fase_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_FASE
	PRIMARY KEY(FASE_ID),
    CONSTRAINT REPETIDO_NOME_FASE
	UNIQUE(fase_nome)
);
CREATE TABLE registos
(
    r_IDMolde INT NOT NULL,
    r_numSensor INT NOT NULL,
    r_fase INT NOT NULL,
    r_data_hora DATETIME NOT NULL,
    r_milissegundos TINYINT NOT NULL,
    r_valor FLOAT,
    CONSTRAINT REPETIDO_REGISTO
	PRIMARY KEY(r_IDMolde, r_numSensor, r_data_hora, r_milissegundos),
    CONSTRAINT REGISTOS_MAU_ID_MOLDE_SENSOR
FOREIGN KEY(r_IDMolde,r_numSensor) REFERENCES sensores(s_IDMolde,s_num)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT REGISTOS_MAU_ID_FASE
FOREIGN KEY(r_fase) REFERENCES fase(fase_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE DATABASE cl_10005;
USE cl_10005;
CREATE TABLE clientes
(
    cl_ID INT NOT NULL,
    cl_nome VARCHAR(50) NOT NULL,
    cl_morada VARCHAR(100),
    cl_IP VARCHAR(50) NOT NULL,
    cl_port INT NOT NULL,
    CONSTRAINT REPETIDO_ID_CLIENTE
	PRIMARY KEY(cl_ID)
);
CREATE TABLE moldes
(
    m_IDCliente INT NOT NULL,
    m_ID INT NOT NULL,
    m_nome VARCHAR(30),
    m_descricao VARCHAR(200),
    CONSTRAINT REPETIDO_ID_MOLDE
	PRIMARY KEY(m_ID),
    CONSTRAINT MOLDE_MAU_ID_CLIENTE
	FOREIGN KEY(m_IDCliente) REFERENCES clientes(cl_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE tipo
(
    tipo_ID INT NOT NULL,
    tipo_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_TIPO
	PRIMARY KEY(tipo_ID),
    CONSTRAINT REPETIDO_NOME_TIPO
	UNIQUE(tipo_nome)
);
CREATE TABLE sensores
(
    s_IDMolde INT NOT NULL,
    s_num INT NOT NULL,
    s_tipo INT NOT NULL,
    s_nome varchar(30),
    s_descricao varchar(200),
    CONSTRAINT REPETIDO_NUM_SENSOR
	PRIMARY KEY(s_IDMolde,s_num),
    CONSTRAINT SENSOR_MAU_ID_MOLDE
	FOREIGN KEY(s_IDMolde) REFERENCES moldes(m_ID)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT SENSOR_MAU_ID_TIPO
	FOREIGN KEY(s_tipo) REFERENCES tipo(tipo_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE fase
(
    fase_ID INT NOT NULL,
    fase_nome VARCHAR(50) NOT NULL,
    CONSTRAINT REPETIDO_ID_FASE
	PRIMARY KEY(FASE_ID),
    CONSTRAINT REPETIDO_NOME_FASE
	UNIQUE(fase_nome)
);
CREATE TABLE registos
(
    r_IDMolde INT NOT NULL,
    r_numSensor INT NOT NULL,
    r_fase INT NOT NULL,
    r_data_hora DATETIME NOT NULL,
    r_milissegundos TINYINT NOT NULL,
    r_valor FLOAT,
    CONSTRAINT REPETIDO_REGISTO
	PRIMARY KEY(r_IDMolde, r_numSensor, r_data_hora, r_milissegundos),
    CONSTRAINT REGISTOS_MAU_ID_MOLDE_SENSOR
FOREIGN KEY(r_IDMolde,r_numSensor) REFERENCES sensores(s_IDMolde,s_num)
		ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT REGISTOS_MAU_ID_FASE
FOREIGN KEY(r_fase) REFERENCES fase(fase_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION
);
