--CREATE SCHEMA moldes;
--GO

CREATE TABLE moldes.clientes(
cl_ID				INT				NOT NULL,
cl_nome				varchar(50)		NOT NULL,
cl_morada			varchar(50)		NOT NULL,
cl_NIF				INT				NOT NULL,
CONSTRAINT REPETIDO_ID_CLIENTE
	PRIMARY KEY(cl_ID),
CONSTRAINT REPETIDO_NIF_CLIENTE
	UNIQUE(cl_NIF),
CONSTRAINT NIF_NAO_ACEITE
	CHECK (cl_NIF >= 100000000 AND cl_NIF <= 999999999)
);
GO

CREATE TABLE moldes.departamentos(
dep_numero			INT				NOT NULL,
dep_nome			VARCHAR(30),
dep_tipo			VARCHAR(30)		NOT NULL,
dep_morada			VARCHAR(100)	NOT NULL,
dep_supervisor		INT,
CONSTRAINT REPETIDO_NUMERO_DEPARTAMENTO
	PRIMARY KEY(dep_numero),
---------FOREIGN KEY(dep_supervisor) REFERENCES moldes.trabalhadores.t_nMec
);
GO

CREATE TABLE moldes.trabalhadores(
t_nMEc				INT				NOT NULL,
t_nome				VARCHAR(80)		NOT NULL,
t_morada			VARCHAR(100)	NOT NULL,
t_departamento		INT				NOT NULL,
CONSTRAINT REPETIDO_NMEC_TRABALHADOR
	PRIMARY KEY(t_nMec),
CONSTRAINT TRABALHADOR_MAU_NUMERO_DEPARTAMENTO
	FOREIGN KEY(t_departamento) REFERENCES moldes.departamentos(dep_numero)
		ON DELETE NO ACTION ON UPDATE NO ACTION--NAO DEIXA FAZER ON DELETE NO ACTION ON UPDATE CASCADE?????????????
);
GO

ALTER TABLE moldes.departamentos
ADD CONSTRAINT DEPARTAMENTO_MAU_NMEC_SUPERVISOR
	FOREIGN KEY(dep_supervisor) REFERENCES moldes.trabalhadores(t_nMec)
		ON DELETE NO ACTION ON UPDATE NO ACTION;--NAO DEIXA FAZER ON DELETE SET NULL ON UPDATE CASCADE?????????????
GO

CREATE TABLE moldes.vendas(
v_num				INT				NOT NULL,
v_cliente			INT				NOT NULL,
v_vendedor			INT,
v_data				DATE			NOT NULL,
CONSTRAINT REPETIDO_NUM_VENDA
	PRIMARY KEY(v_num),
CONSTRAINT VENDA_MAU_NMEC_VENDEDOR
	FOREIGN KEY(v_vendedor) REFERENCES moldes.trabalhadores(t_nMEc)
		ON DELETE SET NULL ON UPDATE CASCADE,
CONSTRAINT VENDA_MAU_ID_CLIENTE
	FOREIGN KEY(v_cliente) REFERENCES moldes.clientes(cl_ID)
		ON DELETE NO ACTION ON UPDATE CASCADE
);
GO

CREATE TABLE moldes.projetos(
p_ID				INT				NOT NULL,
p_lider				INT,
CONSTRAINT REPETIDO_ID_PROJETO
	PRIMARY KEY(p_ID),
CONSTRAINT PROJETO_MAU_NMEC_LIDER
	FOREIGN KEY(p_lider) REFERENCES moldes.trabalhadores(t_nMec)
		ON DELETE SET NULL ON UPDATE CASCADE
);
GO

CREATE TABLE moldes.funcao(
f_ID				INT				NOT NULL,
f_nome				VARCHAR(50)		NOT NULL,
CONSTRAINT REPETIDO_NOME_FUNCAO
	PRIMARY KEY(f_ID)
);
GO

CREATE TABLE moldes.projetam(
p_projeto			INT				NOT NULL,
p_projetista		INT				NOT NULL,
p_funcao			INT				NOT NULL,
p_dataInicio		DATE			NOT NULL,
p_dataFim			DATE,
CONSTRAINT REPETIDO_ID_PROJETO_NMEC_PROJETISTA_E_NOME_FUNCAO
PRIMARY KEY(p_projeto, p_projetista, p_funcao),
CONSTRAINT PROJETAM_MAU_NMEC_PROJETISTA
	FOREIGN KEY(p_projetista) REFERENCES moldes.trabalhadores(t_nMec)
		ON DELETE NO ACTION ON UPDATE NO ACTION,--NAO DEIXA FAZER ON DELETE NO ACTION ON UPDATE CASCADE?????????????
CONSTRAINT PROJETAM_MAU_ID_PROJETO
	FOREIGN KEY(p_projeto) REFERENCES moldes.projetoS(p_ID)
		ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT PROJETAM_MAU_NOME_FUNCAO
	FOREIGN KEY(p_funcao)  REFERENCES moldes.funcao(f_ID)
		ON DELETE NO ACTION ON UPDATE CASCADE
);
GO

CREATE TABLE moldes.tipo(
tipo_ID				INT				NOT NULL,
tipo_nome			VARCHAR(50)		NOT NULL,
CONSTRAINT REPETIDO_NOME_TIPO
	PRIMARY KEY(tipo_ID)
);
GO

CREATE TABLE moldes.estado(
e_ID				INT				NOT NULL,
e_nome				VARCHAR(50)		NOT NULL,
CONSTRAINT REPETIDO_NOME_ESTADO
	PRIMARY KEY(e_ID)
);
GO

CREATE TABLE moldes.moldes(
m_ID				INT				NOT NULL,
m_nome				VARCHAR(30),
m_venda				INT				NOT NULL,
m_garantia			DATE,
m_montante			INT,
m_projeto			INT				NOT NULL,
m_estado			INT				NOT NULL,
m_descricao			VARCHAR(100),
CONSTRAINT REPETIDO_ID_MOLDE
	PRIMARY KEY(m_ID),
CONSTRAINT MOLDE_MAU_NUMERO_VENDA
	FOREIGN KEY(m_venda) REFERENCES moldes.vendas(v_num)
		ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT MOLDE_MAU_ID_PROJETO
	FOREIGN KEY(m_projeto) REFERENCES moldes.projetos(p_ID)
		ON DELETE NO ACTION ON UPDATE NO ACTION,--NAO DEIXA FAZER ON DELETE NO ACTION ON UPDATE CASCADE?????????????
CONSTRAINT MOLDE_MAU_NOME_ESTADO
	FOREIGN KEY(m_estado) REFERENCES moldes.estado(e_ID)
		ON DELETE NO ACTION ON UPDATE CASCADE,
CONSTRAINT MOLDE_VENDA_SEM_MONTANTE_OU_GARANTIA
	CHECK(m_garantia IS NULL AND m_montante IS NULL OR  m_garantia IS NOT NULL AND m_montante IS NOT NULL)
);
GO

CREATE TABLE moldes.sensores(
s_IDMolde			INT				NOT NULL,
s_num				INT				NOT NULL,
s_tipo				INT				NOT NULL,
s_nome				varchar(30),
s_descricao			varchar(200),
CONSTRAINT REPETIDO_NUM_SENSOR
	PRIMARY KEY(s_IDMolde,s_num),
CONSTRAINT SENSOR_MAU_ID_MOLDE
	FOREIGN KEY(s_IDMolde) REFERENCES moldes.moldes(m_ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT SENSOR_MAU_NOME_TIPO
	FOREIGN KEY(s_tipo) REFERENCES moldes.tipo(tipo_ID)
		ON DELETE NO ACTION ON UPDATE CASCADE
);
GO

CREATE TABLE moldes.registos(
r_IDMolde			INT				NOT NULL,
r_numSensor			INT				NOT NULL,
r_data_hora			DATETIME		NOT NULL,
r_milisegundos		TINYINT			NOT NULL,
r_valor				FLOAT,
CONSTRAINT REPETIDO_REGISTO
	PRIMARY KEY(r_IDMolde, r_numSensor, r_data_hora, r_milisegundos),
--CONSTRAINT REGISTOS_MAU_ID_MOLDE
--	FOREIGN KEY(r_IDMolde) REFERENCES moldes.moldes(m_ID)
--		ON DELETE NO ACTION ON UPDATE NO ACTION,--NAO DEIXA FAZER ON DELETE CASCADE ON UPDATE CASCADE?????????????
CONSTRAINT REGISTOS_MAU_NUMERO_SENSOR
FOREIGN KEY(r_IDMolde,r_numSensor) REFERENCES moldes.sensores(s_IDMolde,s_num)
		ON DELETE NO ACTION ON UPDATE NO ACTION--NAO DEIXA FAZER ON DELETE CASCADE ON UPDATE CASCADE?????????????
);
GO

--var y = DATE "20-10-1998"