CREATE USER 'sensores'@'localhost' IDENTIFIED BY 'sensores1234';
GRANT INSERT ON *.registos TO 'sensores'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'transferencia'@'%' IDENTIFIED BY 'transferencia1234';
GRANT SELECT, DELETE ON *.registos TO 'transferencia'@'%';
FLUSH PRIVILEGES;
CREATE USER 'user'@'%' IDENTIFIED BY 'password';
GRANT CREATE ON *.* TO 'user'@'%';
GRANT SELECT, UPDATE, ON *.clientes TO 'user'@'%';
GRANT SELECT, INSERT, DELETE ON *.moldes TO 'user'@'%';
GRANT SELECT, INSERT, DELETE ON *.sensores TO 'user'@'%';
GRANT SELECT ON *.registos TO 'user'@'%';
FLUSH PRIVILEGES;
